/* The following code was generated by CSFlex 1.4 on 04.01.2019 */

#line 1 "Scanner.flex"

namespace RpcNetGen
{
    using System;
    using System.IO;
    using System.Text;
    using TUVienna.CS_CUP.Runtime;


#line default
/**
 * This class is a scanner generated by <a href="http://www.sourceforge.net/projects/csflex/">C# Flex</a>, based on
 * <a href="http://www.jflex.de/">JFlex</a>, version 1.4
 * on 04.01.2019 from the specification file
 * <tt>Scanner.flex</tt>
 */
class Scanner: TUVienna.CS_CUP.Runtime.Scanner {
  /** This character denotes the end of file */
  public const int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private const int ZZ_BUFFERSIZE = 16384;
  /**
   * This is used in 'if' statements to eliminate dead code
   * warnings for 'break;' after the end of a user action
   * block of code. The Java version does this by emitting
   * a second 'case' which is impossible to reach. Since this
   * is impossible for the compiler to deduce during semantic
   * analysis, the warning is stifled. However, C# does not
   * permit 'case' blocks to flow into each other, so the C#
   * output mode needs a different approach. In this case,
   * the entire user code is wrapped up in an 'if' statement
   * whose condition is always true. No warning is emitted
   * because the compiler doesn't strictly propagate the value
   * of 'static readonly' fields, and thus does not semantically
   * detect the fact that the 'if' will always be true.
   */
   public static readonly bool ZZ_SPURIOUS_WARNINGS_SUCK = true;

  /** lexical states */
  public const int YYINITIAL = 0;
  static Scanner()
  {
    ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);
    ZZ_ACTION = zzUnpackAction();
    ZZ_ROWMAP = zzUnpackRowMap();
    ZZ_TRANS = zzUnpackTrans();
    ZZ_ATTRIBUTE = zzUnpackAttribute();
  }


  /** 
   * Translates characters to character classes
   */
  private static readonly ushort[] ZZ_CMAP_PACKED = new ushort[] {
    9, 0, 1, 3, 1, 2, 1, 0, 1, 3, 1, 1, 18, 0, 1, 3, 7, 0, 1, 57,
    1, 58, 1, 5, 1, 0, 1, 54, 1, 12, 1, 0, 1, 4, 1, 7, 1, 44, 1, 49,
    1, 48, 1, 50, 1, 11, 1, 45, 1, 11, 2, 8, 1, 55, 1, 53, 1, 63, 1, 56,
    1, 64, 2, 0, 1, 28, 3, 10, 1, 31, 1, 10, 1, 27, 1, 6, 1, 33, 3, 6,
    1, 29, 1, 34, 1, 26, 1, 24, 1, 6, 1, 25, 1, 32, 1, 6, 1, 47, 1, 30,
    4, 6, 1, 61, 1, 0, 1, 62, 1, 0, 1, 46, 1, 0, 1, 17, 1, 51, 1, 35,
    1, 38, 1, 20, 1, 39, 1, 16, 1, 41, 1, 22, 2, 6, 1, 43, 1, 18, 1, 23,
    1, 15, 1, 13, 1, 52, 1, 14, 1, 21, 1, 36, 1, 42, 1, 19, 1, 40, 1, 9,
    1, 37, 1, 6, 1, 59, 1, 0, 1, 60, 0xff82, 0, 0 };

  /** 
   * Translates characters to character classes
   */
  private static readonly char[] ZZ_CMAP;

  /** 
   * Translates DFA states to action switch labels.
   */
  private static readonly int [] ZZ_ACTION;

  private static readonly ushort[] ZZ_ACTION_PACKED_0 = new ushort[] {
    1, 0, 1, 1, 2, 2, 1, 1, 1, 3, 1, 4, 2, 5, 1, 1,
    19, 4, 1, 6, 1, 7, 1, 8, 1, 9, 1, 10, 1, 11, 1, 12,
    1, 13, 1, 14, 1, 15, 1, 16, 1, 17, 2, 0, 1, 5, 1, 0,
    28, 4, 2, 18, 1, 0, 1, 5, 8, 4, 1, 19, 24, 4, 1, 20,
    1, 4, 1, 21, 13, 4, 1, 22, 1, 23, 5, 4, 1, 24, 6, 4,
    1, 25, 1, 4, 1, 26, 7, 4, 1, 27, 5, 4, 1, 28, 1, 29,
    1, 30, 1, 31, 3, 4, 1, 32, 1, 33, 4, 4, 1, 34, 2, 4,
    1, 35, 8, 4, 1, 36, 1, 4, 1, 37, 1, 38, 1, 39, 6, 4,
    1, 40, 5, 4, 1, 41, 1, 4, 1, 42, 1, 43, 1, 44, 1, 45,
    1, 4, 1, 46, 1, 4, 1, 47, 1, 48, 1, 49, 1, 50, 1, 51,
    1, 52, 1, 53, 1, 54, 1, 55, 4, 4, 1, 56, 1, 57, 1, 4,
    1, 58, 1, 59, 1, 60, 1, 61, 1, 4, 1, 62, 0 };

  private static int [] zzUnpackAction() {
    int [] result = new int[229];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(ushort[] packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.Length;
    while (i + 1 < l) {
      int count = packed[i++];
      int value = packed[i++];
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static readonly int [] ZZ_ROWMAP;

  private static readonly ushort[] ZZ_ROWMAP_PACKED_0 = new ushort[] {
    0, 0, 0, 65, 0, 130, 0, 65, 0, 195, 0, 65, 0, 0x0104, 0, 0x0145,
    0, 0x0186, 0, 0x01c7, 0, 0x0208, 0, 0x0249, 0, 0x028a, 0, 0x02cb, 0, 0x030c, 0, 0x034d,
    0, 0x038e, 0, 0x03cf, 0, 0x0410, 0, 0x0451, 0, 0x0492, 0, 0x04d3, 0, 0x0514, 0, 0x0555,
    0, 0x0596, 0, 0x05d7, 0, 0x0618, 0, 0x0659, 0, 0x069a, 0, 65, 0, 65, 0, 65,
    0, 65, 0, 65, 0, 65, 0, 65, 0, 65, 0, 65, 0, 65, 0, 65,
    0, 65, 0, 0x06db, 0, 0x071c, 0, 0x075d, 0, 0x079e, 0, 0x07df, 0, 0x0820, 0, 0x0861,
    0, 0x08a2, 0, 0x08e3, 0, 0x0924, 0, 0x0965, 0, 0x09a6, 0, 0x09e7, 0, 0x0a28, 0, 0x0a69,
    0, 0x0aaa, 0, 0x0aeb, 0, 0x0b2c, 0, 0x0b6d, 0, 0x0bae, 0, 0x0bef, 0, 0x0c30, 0, 0x0c71,
    0, 0x0cb2, 0, 0x0cf3, 0, 0x0d34, 0, 0x0d75, 0, 0x0db6, 0, 0x0df7, 0, 0x0e38, 0, 0x0e79,
    0, 0x0eba, 0, 0x06db, 0, 65, 0, 0x0efb, 0, 0x079e, 0, 0x0f3c, 0, 0x0f7d, 0, 0x0fbe,
    0, 0x0fff, 0, 0x1040, 0, 0x1081, 0, 0x10c2, 0, 0x1103, 0, 0x1144, 0, 0x1185, 0, 0x11c6,
    0, 0x1207, 0, 0x1248, 0, 0x1289, 0, 0x12ca, 0, 0x130b, 0, 0x134c, 0, 0x138d, 0, 0x13ce,
    0, 0x140f, 0, 0x1450, 0, 0x1491, 0, 0x14d2, 0, 0x1513, 0, 0x1554, 0, 0x1595, 0, 0x15d6,
    0, 0x1617, 0, 0x1658, 0, 0x1699, 0, 0x16da, 0, 0x171b, 0, 0x175c, 0, 0x0104, 0, 0x179d,
    0, 0x0104, 0, 0x17de, 0, 0x181f, 0, 0x1860, 0, 0x18a1, 0, 0x18e2, 0, 0x1923, 0, 0x1964,
    0, 0x19a5, 0, 0x19e6, 0, 0x1a27, 0, 0x1a68, 0, 0x1aa9, 0, 0x1aea, 0, 0x0104, 0, 0x0104,
    0, 0x1b2b, 0, 0x1b6c, 0, 0x1bad, 0, 0x1bee, 0, 0x1c2f, 0, 0x1c70, 0, 0x1cb1, 0, 0x1cf2,
    0, 0x1d33, 0, 0x1d74, 0, 0x1db5, 0, 0x1df6, 0, 0x0104, 0, 0x1e37, 0, 0x1e78, 0, 0x1eb9,
    0, 0x1efa, 0, 0x1f3b, 0, 0x1f7c, 0, 0x1fbd, 0, 0x1ffe, 0, 0x203f, 0, 0x0104, 0, 0x2080,
    0, 0x20c1, 0, 0x2102, 0, 0x2143, 0, 0x2184, 0, 0x0104, 0, 0x0104, 0, 0x0104, 0, 0x0104,
    0, 0x21c5, 0, 0x2206, 0, 0x2247, 0, 0x0104, 0, 0x0104, 0, 0x2288, 0, 0x22c9, 0, 0x230a,
    0, 0x234b, 0, 0x0104, 0, 0x238c, 0, 0x23cd, 0, 0x0104, 0, 0x240e, 0, 0x244f, 0, 0x2490,
    0, 0x24d1, 0, 0x2512, 0, 0x2553, 0, 0x2594, 0, 0x25d5, 0, 0x0104, 0, 0x2616, 0, 0x0104,
    0, 0x0104, 0, 0x0104, 0, 0x2657, 0, 0x2698, 0, 0x26d9, 0, 0x271a, 0, 0x275b, 0, 0x279c,
    0, 0x0104, 0, 0x27dd, 0, 0x281e, 0, 0x285f, 0, 0x28a0, 0, 0x28e1, 0, 0x0104, 0, 0x2922,
    0, 0x0104, 0, 0x0104, 0, 0x0104, 0, 0x0104, 0, 0x2963, 0, 0x0104, 0, 0x29a4, 0, 0x0104,
    0, 0x0104, 0, 0x0104, 0, 0x0104, 0, 0x0104, 0, 0x0104, 0, 0x0104, 0, 0x0104, 0, 0x0104,
    0, 0x29e5, 0, 0x2a26, 0, 0x2a67, 0, 0x2aa8, 0, 0x0104, 0, 0x0104, 0, 0x2ae9, 0, 0x0104,
    0, 0x0104, 0, 0x0104, 0, 0x0104, 0, 0x2b2a, 0, 0x0104, 0 };

  private static int [] zzUnpackRowMap() {
    int [] result = new int[229];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(ushort[] packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.Length;
    while (i + 1 < l) {
      int high = packed[i++] << 16;
      result[j++] = high | packed[i++];
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static readonly int [] ZZ_TRANS;

  private static readonly ushort[] ZZ_TRANS_PACKED_0 = new ushort[] {
    1, 2, 1, 3, 2, 4, 1, 5, 1, 6, 1, 7, 1, 8, 1, 9,
    2, 7, 1, 9, 1, 10, 1, 11, 1, 7, 1, 12, 3, 7, 1, 13,
    1, 14, 1, 15, 1, 16, 1, 7, 1, 17, 5, 7, 1, 18, 2, 7,
    1, 19, 1, 7, 1, 20, 1, 21, 1, 7, 1, 22, 1, 23, 1, 7,
    1, 24, 1, 25, 1, 26, 2, 9, 1, 7, 1, 27, 3, 9, 1, 28,
    1, 29, 1, 30, 1, 31, 1, 32, 1, 33, 1, 34, 1, 35, 1, 36,
    1, 37, 1, 38, 1, 39, 1, 40, 1, 41, 67, 0, 1, 4, 66, 0,
    1, 42, 1, 43, 65, 0, 6, 7, 1, 0, 40, 7, 19, 0, 1, 44,
    1, 0, 1, 45, 1, 0, 1, 44, 32, 0, 2, 44, 2, 0, 3, 44,
    21, 0, 2, 9, 2, 0, 1, 9, 32, 0, 2, 9, 2, 0, 3, 9,
    22, 0, 1, 9, 2, 0, 1, 9, 32, 0, 2, 9, 2, 0, 3, 9,
    20, 0, 6, 7, 1, 0, 1, 7, 1, 46, 38, 7, 18, 0, 6, 7,
    1, 0, 1, 47, 39, 7, 18, 0, 6, 7, 1, 0, 2, 7, 1, 48,
    4, 7, 1, 49, 32, 7, 18, 0, 6, 7, 1, 0, 10, 7, 1, 50,
    29, 7, 18, 0, 6, 7, 1, 0, 23, 7, 1, 51, 3, 7, 1, 52,
    1, 53, 11, 7, 18, 0, 6, 7, 1, 0, 10, 7, 1, 54, 29, 7,
    18, 0, 6, 7, 1, 0, 12, 7, 1, 55, 27, 7, 18, 0, 6, 7,
    1, 0, 18, 7, 1, 56, 21, 7, 18, 0, 6, 7, 1, 0, 10, 7,
    1, 57, 29, 7, 18, 0, 6, 7, 1, 0, 2, 7, 1, 58, 1, 7,
    1, 59, 23, 7, 1, 60, 11, 7, 18, 0, 6, 7, 1, 0, 24, 7,
    1, 61, 15, 7, 18, 0, 6, 7, 1, 0, 2, 7, 1, 62, 4, 7,
    1, 63, 32, 7, 18, 0, 6, 7, 1, 0, 30, 7, 1, 64, 9, 7,
    18, 0, 6, 7, 1, 0, 24, 7, 1, 65, 15, 7, 18, 0, 6, 7,
    1, 0, 9, 7, 1, 66, 1, 67, 17, 7, 1, 68, 4, 7, 1, 69,
    6, 7, 18, 0, 6, 7, 1, 0, 2, 7, 1, 70, 37, 7, 18, 0,
    6, 7, 1, 0, 20, 7, 1, 71, 19, 7, 18, 0, 6, 7, 1, 0,
    2, 7, 1, 72, 37, 7, 18, 0, 6, 7, 1, 0, 29, 7, 1, 73,
    10, 7, 12, 0, 1, 42, 1, 74, 1, 75, 62, 42, 5, 43, 1, 76,
    59, 43, 7, 0, 1, 44, 3, 0, 1, 44, 32, 0, 2, 44, 2, 0,
    3, 44, 21, 0, 2, 77, 1, 0, 2, 77, 5, 0, 1, 77, 2, 0,
    1, 77, 7, 0, 1, 77, 2, 0, 1, 77, 3, 0, 1, 77, 2, 0,
    2, 77, 4, 0, 2, 77, 2, 0, 4, 77, 19, 0, 6, 7, 1, 0,
    2, 7, 1, 78, 37, 7, 18, 0, 6, 7, 1, 0, 4, 7, 1, 79,
    35, 7, 18, 0, 6, 7, 1, 0, 9, 7, 1, 80, 30, 7, 18, 0,
    6, 7, 1, 0, 1, 7, 1, 81, 38, 7, 18, 0, 6, 7, 1, 0,
    29, 7, 1, 82, 10, 7, 18, 0, 6, 7, 1, 0, 1, 7, 1, 83,
    38, 7, 18, 0, 6, 7, 1, 0, 9, 7, 1, 84, 30, 7, 18, 0,
    6, 7, 1, 0, 2, 7, 1, 85, 37, 7, 18, 0, 6, 7, 1, 0,
    23, 7, 1, 86, 16, 7, 18, 0, 6, 7, 1, 0, 13, 7, 1, 87,
    26, 7, 18, 0, 6, 7, 1, 0, 12, 7, 1, 88, 27, 7, 18, 0,
    6, 7, 1, 0, 23, 7, 1, 89, 16, 7, 18, 0, 6, 7, 1, 0,
    10, 7, 1, 90, 29, 7, 18, 0, 6, 7, 1, 0, 8, 7, 1, 91,
    31, 7, 18, 0, 6, 7, 1, 0, 4, 7, 1, 92, 35, 7, 18, 0,
    6, 7, 1, 0, 1, 93, 39, 7, 18, 0, 6, 7, 1, 0, 29, 7,
    1, 94, 10, 7, 18, 0, 6, 7, 1, 0, 26, 7, 1, 95, 13, 7,
    18, 0, 6, 7, 1, 0, 2, 7, 1, 96, 37, 7, 18, 0, 6, 7,
    1, 0, 1, 97, 39, 7, 18, 0, 6, 7, 1, 0, 10, 7, 1, 98,
    29, 7, 18, 0, 6, 7, 1, 0, 8, 7, 1, 99, 1, 100, 30, 7,
    18, 0, 6, 7, 1, 0, 24, 7, 1, 101, 15, 7, 18, 0, 6, 7,
    1, 0, 8, 7, 1, 102, 1, 103, 20, 7, 1, 104, 9, 7, 18, 0,
    6, 7, 1, 0, 10, 7, 1, 105, 29, 7, 18, 0, 6, 7, 1, 0,
    10, 7, 1, 106, 29, 7, 18, 0, 6, 7, 1, 0, 2, 7, 1, 107,
    37, 7, 18, 0, 6, 7, 1, 0, 4, 7, 1, 108, 35, 7, 12, 0,
    4, 43, 1, 75, 1, 76, 59, 43, 6, 0, 6, 7, 1, 0, 3, 7,
    1, 109, 36, 7, 18, 0, 6, 7, 1, 0, 39, 7, 1, 110, 18, 0,
    6, 7, 1, 0, 25, 7, 1, 111, 14, 7, 18, 0, 6, 7, 1, 0,
    8, 7, 1, 112, 31, 7, 18, 0, 6, 7, 1, 0, 5, 7, 1, 113,
    34, 7, 18, 0, 6, 7, 1, 0, 9, 7, 1, 114, 19, 7, 1, 115,
    10, 7, 18, 0, 6, 7, 1, 0, 23, 7, 1, 116, 16, 7, 18, 0,
    6, 7, 1, 0, 1, 7, 1, 117, 38, 7, 18, 0, 6, 7, 1, 0,
    31, 7, 1, 118, 1, 119, 2, 7, 1, 120, 4, 7, 18, 0, 6, 7,
    1, 0, 14, 7, 1, 121, 25, 7, 18, 0, 6, 7, 1, 0, 19, 7,
    1, 122, 20, 7, 18, 0, 6, 7, 1, 0, 31, 7, 1, 123, 1, 124,
    2, 7, 1, 125, 4, 7, 18, 0, 6, 7, 1, 0, 8, 7, 1, 126,
    31, 7, 18, 0, 6, 7, 1, 0, 7, 7, 1, 127, 32, 7, 18, 0,
    6, 7, 1, 0, 1, 7, 1, 128, 38, 7, 18, 0, 6, 7, 1, 0,
    7, 7, 1, 129, 32, 7, 18, 0, 6, 7, 1, 0, 38, 7, 1, 130,
    1, 7, 18, 0, 6, 7, 1, 0, 4, 7, 1, 131, 35, 7, 18, 0,
    6, 7, 1, 0, 4, 7, 1, 132, 35, 7, 18, 0, 6, 7, 1, 0,
    7, 7, 1, 133, 32, 7, 18, 0, 6, 7, 1, 0, 23, 7, 1, 134,
    16, 7, 18, 0, 6, 7, 1, 0, 9, 7, 1, 135, 30, 7, 18, 0,
    6, 7, 1, 0, 2, 7, 1, 136, 37, 7, 18, 0, 6, 7, 1, 0,
    1, 137, 39, 7, 18, 0, 6, 7, 1, 0, 28, 7, 1, 138, 11, 7,
    18, 0, 6, 7, 1, 0, 10, 7, 1, 139, 29, 7, 18, 0, 6, 7,
    1, 0, 2, 7, 1, 140, 37, 7, 18, 0, 6, 7, 1, 0, 3, 7,
    1, 141, 36, 7, 18, 0, 6, 7, 1, 0, 23, 7, 1, 142, 16, 7,
    18, 0, 6, 7, 1, 0, 30, 7, 1, 143, 9, 7, 18, 0, 6, 7,
    1, 0, 25, 7, 1, 144, 14, 7, 18, 0, 6, 7, 1, 0, 1, 7,
    1, 145, 38, 7, 18, 0, 6, 7, 1, 0, 29, 7, 1, 146, 10, 7,
    18, 0, 6, 7, 1, 0, 9, 7, 1, 147, 30, 7, 18, 0, 6, 7,
    1, 0, 10, 7, 1, 148, 29, 7, 18, 0, 6, 7, 1, 0, 22, 7,
    1, 149, 17, 7, 18, 0, 6, 7, 1, 0, 22, 7, 1, 150, 17, 7,
    18, 0, 6, 7, 1, 0, 23, 7, 1, 151, 16, 7, 18, 0, 6, 7,
    1, 0, 32, 7, 1, 152, 7, 7, 18, 0, 6, 7, 1, 0, 37, 7,
    1, 153, 2, 7, 18, 0, 6, 7, 1, 0, 36, 7, 1, 154, 3, 7,
    18, 0, 6, 7, 1, 0, 12, 7, 1, 155, 27, 7, 18, 0, 6, 7,
    1, 0, 20, 7, 1, 156, 19, 7, 18, 0, 6, 7, 1, 0, 32, 7,
    1, 157, 7, 7, 18, 0, 6, 7, 1, 0, 37, 7, 1, 158, 2, 7,
    18, 0, 6, 7, 1, 0, 36, 7, 1, 159, 3, 7, 18, 0, 6, 7,
    1, 0, 23, 7, 1, 160, 16, 7, 18, 0, 6, 7, 1, 0, 25, 7,
    1, 161, 14, 7, 18, 0, 6, 7, 1, 0, 30, 7, 1, 162, 9, 7,
    18, 0, 6, 7, 1, 0, 29, 7, 1, 163, 10, 7, 18, 0, 6, 7,
    1, 0, 23, 7, 1, 164, 16, 7, 18, 0, 6, 7, 1, 0, 1, 7,
    1, 165, 38, 7, 18, 0, 6, 7, 1, 0, 31, 7, 1, 166, 1, 167,
    2, 7, 1, 168, 4, 7, 18, 0, 6, 7, 1, 0, 3, 7, 1, 169,
    36, 7, 18, 0, 6, 7, 1, 0, 10, 7, 1, 170, 29, 7, 18, 0,
    6, 7, 1, 0, 7, 7, 1, 171, 32, 7, 18, 0, 6, 7, 1, 0,
    2, 7, 1, 172, 37, 7, 18, 0, 6, 7, 1, 0, 23, 7, 1, 173,
    16, 7, 18, 0, 6, 7, 1, 0, 10, 7, 1, 174, 29, 7, 18, 0,
    6, 7, 1, 0, 31, 7, 1, 175, 1, 176, 2, 7, 1, 177, 4, 7,
    18, 0, 6, 7, 1, 0, 7, 7, 1, 178, 25, 7, 1, 179, 6, 7,
    18, 0, 6, 7, 1, 0, 1, 7, 1, 180, 38, 7, 18, 0, 6, 7,
    1, 0, 4, 7, 1, 181, 35, 7, 18, 0, 6, 7, 1, 0, 7, 7,
    1, 182, 32, 7, 18, 0, 6, 7, 1, 0, 2, 7, 1, 183, 37, 7,
    18, 0, 6, 7, 1, 0, 3, 7, 1, 184, 36, 7, 18, 0, 6, 7,
    1, 0, 23, 7, 1, 185, 16, 7, 18, 0, 6, 7, 1, 0, 28, 7,
    1, 186, 11, 7, 18, 0, 6, 7, 1, 0, 33, 7, 1, 187, 6, 7,
    18, 0, 6, 7, 1, 0, 33, 7, 1, 188, 6, 7, 18, 0, 6, 7,
    1, 0, 33, 7, 1, 189, 6, 7, 18, 0, 6, 7, 1, 0, 15, 7,
    1, 190, 24, 7, 18, 0, 6, 7, 1, 0, 13, 7, 1, 191, 26, 7,
    18, 0, 6, 7, 1, 0, 7, 7, 1, 192, 32, 7, 18, 0, 6, 7,
    1, 0, 7, 7, 1, 193, 32, 7, 18, 0, 6, 7, 1, 0, 30, 7,
    1, 194, 9, 7, 18, 0, 6, 7, 1, 0, 32, 7, 1, 195, 7, 7,
    18, 0, 6, 7, 1, 0, 37, 7, 1, 196, 2, 7, 18, 0, 6, 7,
    1, 0, 36, 7, 1, 197, 3, 7, 18, 0, 6, 7, 1, 0, 10, 7,
    1, 198, 29, 7, 18, 0, 6, 7, 1, 0, 1, 7, 1, 199, 38, 7,
    18, 0, 6, 7, 1, 0, 1, 7, 1, 200, 38, 7, 18, 0, 6, 7,
    1, 0, 3, 7, 1, 201, 36, 7, 18, 0, 6, 7, 1, 0, 32, 7,
    1, 202, 7, 7, 18, 0, 6, 7, 1, 0, 37, 7, 1, 203, 2, 7,
    18, 0, 6, 7, 1, 0, 36, 7, 1, 204, 3, 7, 18, 0, 6, 7,
    1, 0, 4, 7, 1, 205, 35, 7, 18, 0, 6, 7, 1, 0, 23, 7,
    1, 206, 16, 7, 18, 0, 6, 7, 1, 0, 29, 7, 1, 207, 10, 7,
    18, 0, 6, 7, 1, 0, 5, 7, 1, 208, 34, 7, 18, 0, 6, 7,
    1, 0, 10, 7, 1, 209, 29, 7, 18, 0, 6, 7, 1, 0, 23, 7,
    1, 210, 16, 7, 18, 0, 6, 7, 1, 0, 23, 7, 1, 211, 16, 7,
    18, 0, 6, 7, 1, 0, 23, 7, 1, 212, 16, 7, 18, 0, 6, 7,
    1, 0, 16, 7, 1, 213, 23, 7, 18, 0, 6, 7, 1, 0, 21, 7,
    1, 214, 18, 7, 18, 0, 6, 7, 1, 0, 26, 7, 1, 215, 13, 7,
    18, 0, 6, 7, 1, 0, 23, 7, 1, 216, 16, 7, 18, 0, 6, 7,
    1, 0, 33, 7, 1, 217, 6, 7, 18, 0, 6, 7, 1, 0, 33, 7,
    1, 218, 6, 7, 18, 0, 6, 7, 1, 0, 33, 7, 1, 219, 6, 7,
    18, 0, 6, 7, 1, 0, 7, 7, 1, 220, 32, 7, 18, 0, 6, 7,
    1, 0, 23, 7, 1, 221, 16, 7, 18, 0, 6, 7, 1, 0, 10, 7,
    1, 222, 29, 7, 18, 0, 6, 7, 1, 0, 1, 223, 39, 7, 18, 0,
    6, 7, 1, 0, 23, 7, 1, 224, 16, 7, 18, 0, 6, 7, 1, 0,
    23, 7, 1, 225, 16, 7, 18, 0, 6, 7, 1, 0, 23, 7, 1, 226,
    16, 7, 18, 0, 6, 7, 1, 0, 25, 7, 1, 227, 14, 7, 18, 0,
    6, 7, 1, 0, 30, 7, 1, 228, 9, 7, 18, 0, 6, 7, 1, 0,
    7, 7, 1, 229, 32, 7, 12, 0, 0 };

  private static int [] zzUnpackTrans() {
    int [] result = new int[11115];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(ushort[] packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.Length;
    while (i + 1 < l) {
      int count = packed[i++];
      int value = packed[i++];
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private const int ZZ_UNKNOWN_ERROR = 0;
  private const int ZZ_NO_MATCH = 1;
  private const int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static readonly String[] ZZ_ERROR_MSG = new string[] {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static readonly int [] ZZ_ATTRIBUTE;

  private static readonly ushort[] ZZ_ATTRIBUTE_PACKED_0 = new ushort[] {
    1, 0, 1, 9, 1, 1, 1, 9, 1, 1, 1, 9, 23, 1, 12, 9,
    2, 0, 1, 1, 1, 0, 29, 1, 1, 9, 1, 0, 153, 1, 0 };

  private static int [] zzUnpackAttribute() {
    int [] result = new int[229];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(ushort[] packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.Length;
    while (i + 1 < l) {
      int count = packed[i++];
      int value = packed[i++];
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private System.IO.TextReader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char[] zzBuffer = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private bool zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private bool zzEOFDone;

  /* user code: */
    StringBuilder strng = new StringBuilder();

    private Symbol symbol(int type)
    {
        return new Symbol(type, yyline + 1, yycolumn + 1);
    }

    private Symbol symbol(int type, object value)
    {
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
    }


  /**
   * Creates a new scanner
   * There is also a System.IO.Stream version of this constructor.
   *
   * @param   in  the System.IO.TextReader to read input from.
   */
  internal Scanner(TextReader @in) {
    this.zzReader = @in;
  }

  /**
   * Creates a new scanner.
   * There is also TextReader version of this constructor.
   *
   * @param   in  the System.IO.Stream to read input from.
   */
  internal Scanner(Stream @in) : this(new StreamReader(@in))
  {
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(ushort[] packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 172) {
      int  count = packed[i++];
      char value = (char)packed[i++];
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private bool zzRefill() {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      Array.Copy(zzBuffer, zzStartRead,
                 zzBuffer, 0,
                 zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.Length) {
      /* if not: blow it up */
      char[] newBuffer = new char[zzCurrentPos*2];
      Array.Copy(zzBuffer, 0, newBuffer, 0, zzBuffer.Length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.Read(zzBuffer, zzEndRead,
                                            zzBuffer.Length-zzEndRead);

    if (numRead <= 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public void yyclose() {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.Close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public void yyreset(System.IO.TextReader reader) {
    zzReader = reader;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex/CSFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (IndexOutOfRangeException) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Exception(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
        yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   System.IO.IOException  if any I/O-Error occurs
   */
  public TUVienna.CS_CUP.Runtime.Symbol next_token() {
    int zzInput = 0;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      bool zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
          break;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        bool zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          bool eof = zzRefill();
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


        while (true) {
          goto zzForAction_skip;
        zzForAction: break;
        zzForAction_skip:
          if (!ZZ_SPURIOUS_WARNINGS_SUCK) goto zzForAction;
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            goto zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            bool eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
            goto zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) goto zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) goto zzForAction;
          }

        }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 57: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 121 "Scanner.flex"
                          return symbol(Symbols.BOOL); 
#line default
          }
          break;
        case 45: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 107 "Scanner.flex"
                          return symbol(Symbols.UINT); 
#line default
          }
          break;
        case 26: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 120 "Scanner.flex"
                          return symbol(Symbols.BOOL); 
#line default
          }
          break;
        case 61: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 130 "Scanner.flex"
                          return symbol(Symbols.UNSIGNED); 
#line default
          }
          break;
        case 54: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 87 "Scanner.flex"
                          return symbol(Symbols.TYPEDEF); 
#line default
          }
          break;
        case 8: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 135 "Scanner.flex"
                          return symbol(Symbols.COLON); 
#line default
          }
          break;
        case 34: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 127 "Scanner.flex"
                          return symbol(Symbols.UNION); 
#line default
          }
          break;
        case 31: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 86 "Scanner.flex"
                          return symbol(Symbols.CONST); 
#line default
          }
          break;
        case 59: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 116 "Scanner.flex"
                          return symbol(Symbols.UHYPER); 
#line default
          }
          break;
        case 16: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 144 "Scanner.flex"
                          return symbol(Symbols.LANGLE); 
#line default
          }
          break;
        case 43: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 100 "Scanner.flex"
                          return symbol(Symbols.USHORT); 
#line default
          }
          break;
        case 42: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 110 "Scanner.flex"
                          return symbol(Symbols.ULONG); 
#line default
          }
          break;
        case 28: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 97 "Scanner.flex"
                          return symbol(Symbols.SHORT); 
#line default
          }
          break;
        case 53: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 84 "Scanner.flex"
                          return symbol(Symbols.VERSION); 
#line default
          }
          break;
        case 60: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 108 "Scanner.flex"
                          return symbol(Symbols.UINT); 
#line default
          }
          break;
        case 1: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 162 "Scanner.flex"
                          throw new InvalidOperationException("Illegal character \"" + yytext() + "\""); 
#line default
          }
          break;
        case 5: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 148 "Scanner.flex"
                       
        return symbol(Symbols.INTEGER_LITERAL, yytext());
    
#line default
          }
          break;
        case 52: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 83 "Scanner.flex"
                          return symbol(Symbols.PROGRAM); 
#line default
          }
          break;
        case 46: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 122 "Scanner.flex"
                          return symbol(Symbols.BOOL); 
#line default
          }
          break;
        case 39: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 89 "Scanner.flex"
                          return symbol(Symbols.SWITCH); 
#line default
          }
          break;
        case 36: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 124 "Scanner.flex"
                          return symbol(Symbols.OPAQUE); 
#line default
          }
          break;
        case 47: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 81 "Scanner.flex"
                          return symbol(Symbols.PROGRAM); 
#line default
          }
          break;
        case 33: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 111 "Scanner.flex"
                          return symbol(Symbols.HYPER); 
#line default
          }
          break;
        case 19: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 102 "Scanner.flex"
                          return symbol(Symbols.INT); 
#line default
          }
          break;
        case 13: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 141 "Scanner.flex"
                          return symbol(Symbols.RBRACE); 
#line default
          }
          break;
        case 56: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 99 "Scanner.flex"
                          return symbol(Symbols.USHORT); 
#line default
          }
          break;
        case 40: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 118 "Scanner.flex"
                          return symbol(Symbols.DOUBLE); 
#line default
          }
          break;
        case 32: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 117 "Scanner.flex"
                          return symbol(Symbols.FLOAT); 
#line default
          }
          break;
        case 11: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 139 "Scanner.flex"
                          return symbol(Symbols.RPAREN); 
#line default
          }
          break;
        case 7: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 134 "Scanner.flex"
                          return symbol(Symbols.COMMA); 
#line default
          }
          break;
        case 27: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 96 "Scanner.flex"
                          return symbol(Symbols.SHORT); 
#line default
          }
          break;
        case 18: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 159 "Scanner.flex"
                        /* ignore */ 
#line default
          }
          break;
        case 41: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 114 "Scanner.flex"
                          return symbol(Symbols.UHYPER); 
#line default
          }
          break;
        case 20: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 94 "Scanner.flex"
                          return symbol(Symbols.VOID); 
#line default
          }
          break;
        case 58: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 101 "Scanner.flex"
                          return symbol(Symbols.USHORT); 
#line default
          }
          break;
        case 51: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 104 "Scanner.flex"
                          return symbol(Symbols.INT); 
#line default
          }
          break;
        case 38: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 126 "Scanner.flex"
                          return symbol(Symbols.STRUCT); 
#line default
          }
          break;
        case 10: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 138 "Scanner.flex"
                          return symbol(Symbols.LPAREN); 
#line default
          }
          break;
        case 4: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 153 "Scanner.flex"
                  
        return symbol(Symbols.IDENTIFIER, yytext());
    
#line default
          }
          break;
        case 17: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 145 "Scanner.flex"
                          return symbol(Symbols.RANGLE); 
#line default
          }
          break;
        case 25: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 109 "Scanner.flex"
                          return symbol(Symbols.LONG); 
#line default
          }
          break;
        case 24: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 105 "Scanner.flex"
                          return symbol(Symbols.UINT); 
#line default
          }
          break;
        case 15: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 143 "Scanner.flex"
                          return symbol(Symbols.RBRACKET); 
#line default
          }
          break;
        case 44: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 115 "Scanner.flex"
                          return symbol(Symbols.UHYPER); 
#line default
          }
          break;
        case 3: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 137 "Scanner.flex"
                          return symbol(Symbols.STAR); 
#line default
          }
          break;
        case 48: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 82 "Scanner.flex"
                          return symbol(Symbols.VERSION); 
#line default
          }
          break;
        case 6: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 133 "Scanner.flex"
                          return symbol(Symbols.SEMICOLON); 
#line default
          }
          break;
        case 12: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 140 "Scanner.flex"
                          return symbol(Symbols.LBRACE); 
#line default
          }
          break;
        case 30: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 103 "Scanner.flex"
                          return symbol(Symbols.INT); 
#line default
          }
          break;
        case 21: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 123 "Scanner.flex"
                          return symbol(Symbols.ENUM); 
#line default
          }
          break;
        case 62: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 119 "Scanner.flex"
                          return symbol(Symbols.QUADRUPLE); 
#line default
          }
          break;
        case 35: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 106 "Scanner.flex"
                          return symbol(Symbols.UINT); 
#line default
          }
          break;
        case 49: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 98 "Scanner.flex"
                          return symbol(Symbols.SHORT); 
#line default
          }
          break;
        case 55: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 91 "Scanner.flex"
                          return symbol(Symbols.DEFAULT); 
#line default
          }
          break;
        case 29: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 112 "Scanner.flex"
                          return symbol(Symbols.HYPER); 
#line default
          }
          break;
        case 50: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 113 "Scanner.flex"
                          return symbol(Symbols.HYPER); 
#line default
          }
          break;
        case 2: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 158 "Scanner.flex"
                          /* ignore */ 
#line default
          }
          break;
        case 37: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 125 "Scanner.flex"
                          return symbol(Symbols.STRING); 
#line default
          }
          break;
        case 14: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 142 "Scanner.flex"
                          return symbol(Symbols.LBRACKET); 
#line default
          }
          break;
        case 23: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 95 "Scanner.flex"
                          return symbol(Symbols.CHAR); 
#line default
          }
          break;
        case 22: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 90 "Scanner.flex"
                          return symbol(Symbols.CASE); 
#line default
          }
          break;
        case 9: 
          if (ZZ_SPURIOUS_WARNINGS_SUCK)
          {
#line 136 "Scanner.flex"
                          return symbol(Symbols.EQUAL); 
#line default
          }
          break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              if (ZZ_SPURIOUS_WARNINGS_SUCK)
              {     return new Symbol(Symbols.EOF);
 }
              break;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
          break;
      }
    }
  }


}
#line 165 "Scanner.flex"

}

/* End of file Scanner.flex */

#line default
