
//----------------------------------------------------
// The following code was generated by C# CUP v0.1
// 04.01.2019 12:42:46
//----------------------------------------------------

namespace RpcNetGen
{

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public const int ULONG = 29;
  public const int VERSION = 16;
  public const int TYPEDEF = 18;
  public const int DEFAULT = 21;
  public const int COLON = 4;
  public const int DOUBLE = 33;
  public const int SWITCH = 19;
  public const int LBRACKET = 11;
  public const int RBRACE = 10;
  public const int RPAREN = 8;
  public const int COMMA = 3;
  public const int UNSIGNED = 41;
  public const int STAR = 6;
  public const int IDENTIFIER = 43;
  public const int SEMICOLON = 2;
  public const int OPAQUE = 37;
  public const int CHAR = 23;
  public const int LBRACE = 9;
  public const int FLOAT = 32;
  public const int BOOL = 35;
  public const int QUADRUPLE = 34;
  public const int STRING = 38;
  public const int STRUCT = 39;
  public const int LPAREN = 7;
  public const int RANGLE = 14;
  public const int LONG = 28;
  public const int ENUM = 36;
  public const int RBRACKET = 12;
  public const int VOID = 22;
  public const int EQUAL = 5;
  public const int UINT = 27;
  public const int LANGLE = 13;
  public const int UHYPER = 31;
  public const int HYPER = 30;
  public const int INTEGER_LITERAL = 42;
  public const int UNION = 40;
  public const int CONST = 17;
  public const int INT = 26;
  public const int CASE = 20;
  public const int USHORT = 25;
  public const int EOF = 0;
  public const int error = 1;
  public const int SHORT = 24;
  public const int PROGRAM = 15;
	}
}
